### ISSUE TITLE
The label of the dataset is not binary map.

### ISSUE THREAD

**Issue by wenhwu** [daifeng2016/End-to-end-CD-for-VHR-satellite-image#11]
Thank you for your generous sharing！

I downloaded the dataset mentioned in your paper, but found that the label of the dataset was not  binary map, as [Issue in label dataset of 2018. Lebedev M A, Vizilter Y V, Vygolov O V, et al. Change detection in remote sensing images using conditional adversarial networks](https://github.com/wenhwu/awesome-remote-sensing-change-detection/issues/5) said. 

How did you deal with this situation ?

thanks

**Comment by Bobholamovic** [comment]
This is quite a problem. I guess the reason lies in the *jpeg* compression, which sort of spreads the histogram. 

For binarization, I tried `(CM==255)`, which introduces noticeable holes inside white region, and `(CM>127)`, which looks better than the former one except that the while region dilates a little bit. I guess adaptive thresholding methods like OTSU could achieve better result, but I think it would be quite weired that we have to segment these non-binary gt maps like that. So, I'm seeking for a simpler solution. I've emailed the authors of this dataset about this, yet haven't received any useful reply.  😰

**Comment by wenhwu** [comment]
Thank you very much for your details, but I don't think it is necessary to restore this dataset into the true binary map, because it is expected that no current method can accurately obtain the change boundary of the binary map. Instead of taking the time to correct the errors in this dataset, we might as well re-create a change detection dataset.

Moreover, I find that the change detection datasets published so far may be sufficient to meet our needs, such as [LEVIR-CD](https://justchenhao.github.io/LEVIR/) and [HRSCD](https://ieee-dataport.org/open-access/hrscd-high-resolution-semantic-change-detection-dataset).

 I'm closing the issue, but let me know if you have further questions.
